title: Carlos Quintos Nores
logo:
email: 90f0ad@gmail.com
lang: es-ES
description: I'm a Linux and Open Source lover
favicon: true
color-scheme: auto
remote_theme: vaibhavvikas/jekyll-theme-minimalistic

platforms:
  - name: Resume
    icon: <i class="fa-solid fa-file-lines"></i>
    link: ./carlosquintos-cv.pdf
  - name: Routine
    icon: <i class="fa-solid fa-file-lines"></i>
    link: ./routine.pdf
  - name: Gitlab
    icon: <i class="fa-brands fa-gitlab"></i>
    link: https://gitlab.com/cqnpvp
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/cqnpvp/
  - name: Twitter
    icon: <i class="fa-brands fa-twitter"></i>
    link: https://twitter.com/cqnpvp/
  - name: YouTube
    icon: <i class="fa-brands fa-youtube"></i>
    link: https://www.youtube.com/@cqnpvp
  - name: Instagram
    icon: <i class="fa-brands fa-instagram"></i>
    link: https://www.instagram.com/cqnpvp/

navigation:      
  - name: Work Experience
    link: ./index.html#work-experience
  - name: Education and Training
    link: ./index.html#education-and-training
  - name: Language Skills
    link: ./index.html#language-skills
  - name: Digital Skills
    link: ./index.html#digital-skills